### ISSUE TITLE
AE2 Defragmentation?

### ISSUE THREAD

**Issue by sci4me** [OpenMods/OpenPeripheral-Integration#9]
So this (https://www.youtube.com/watch?v=NetjdOtNZBc) is something I am interested in doing. I notice a function called "condenseItems" which can be called on AE2 controllers. My question is does "condenseItems" do defragmenting in AE2 storage (drives)? If not, can it be done with a ComputerCraft computer?

**Comment by boq** [comment]
`condenseItems` is from vanilla inventories ([source](https://github.com/OpenMods/OpenPeripheral-Integration/blob/master/src/main/java/openperipheral/integration/vanilla/AdapterInventory.java#L51)). It only merges stacks in attached inventory, so it does not work on AE2.

It's probably impossible to defragment with OP, since we don't give any information about item location.
